/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface EthdocsRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addCertificate"
      | "certificates"
      | "owner"
      | "verifyCertificate"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "CertificateAdded"): EventFragment;

  encodeFunctionData(
    functionFragment: "addCertificate",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "certificates",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "verifyCertificate",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "addCertificate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "certificates",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "verifyCertificate",
    data: BytesLike
  ): Result;
}

export namespace CertificateAddedEvent {
  export type InputTuple = [certHash: BytesLike];
  export type OutputTuple = [certHash: string];
  export interface OutputObject {
    certHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EthdocsRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): EthdocsRegistry;
  waitForDeployment(): Promise<this>;

  interface: EthdocsRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addCertificate: TypedContractMethod<
    [certHash: BytesLike],
    [void],
    "nonpayable"
  >;

  certificates: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  verifyCertificate: TypedContractMethod<
    [certHash: BytesLike],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addCertificate"
  ): TypedContractMethod<[certHash: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "certificates"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "verifyCertificate"
  ): TypedContractMethod<[certHash: BytesLike], [boolean], "view">;

  getEvent(
    key: "CertificateAdded"
  ): TypedContractEvent<
    CertificateAddedEvent.InputTuple,
    CertificateAddedEvent.OutputTuple,
    CertificateAddedEvent.OutputObject
  >;

  filters: {
    "CertificateAdded(bytes32)": TypedContractEvent<
      CertificateAddedEvent.InputTuple,
      CertificateAddedEvent.OutputTuple,
      CertificateAddedEvent.OutputObject
    >;
    CertificateAdded: TypedContractEvent<
      CertificateAddedEvent.InputTuple,
      CertificateAddedEvent.OutputTuple,
      CertificateAddedEvent.OutputObject
    >;
  };
}
