/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { EthdocsRegistry } from "./EthdocsRegistry";
export * as factories from "./factories";
export { EthdocsRegistry__factory } from "./factories/EthdocsRegistry__factory";
